name: tf-cpu

dependencies:
  - python==3.8
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python==4.4.0.44
    - lxml
    - tqdm
    - tensorflow==2.3.1
    - absl-py
    - easydict
    - pillow
    - imutils
    - scipy